version: '3'
services:
  frontend:
    build:
      context: "."
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
      - "24678:24678"
    # restart: always