version: '3'
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www/html
    networks:
      - laravel-nuxt-network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app/
      # - /usr/src/app/node_modules
      # - ./front-end/node_modules:/usr/src/app/node_modules

    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - laravel-nuxt-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel-nuxt-network
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - laravel-nuxt-network

networks:
  laravel-nuxt-network: