version: '3'
services:
  php-fpm:
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./client:/var/www/html/client
      - /var/www/html/client/node_modules
    ports:
      - "3000:3000"
      - "24678:24678"
    networks:
      - laravel
  mysql:
    image: mysql:5.7
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - php-fpm
    networks:
      - laravel
networks:
  laravel: